name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y postgresql libpq-dev libglfw3 libglfw3-dev libfreetype6-dev libssl-dev sqlite3 libsqlite3-dev valgrind
    - name: Download V
      run: |
        tag=${GITHUB_REF##*/}
        wget https://github.com/vlang/v/releases/download/$tag/v_linux.zip
        unzip v_linux.zip
        cd v
        sudo ./v symlink
    - name: Run tests
      run: |
        v test .
