name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y sudo build-essential libssl-dev libgc-dev unzip
    - name: Download V
      run: |
        cd ..
        wget https://github.com/vlang/v/releases/latest/download/v_linux.zip 
        unzip v_linux.zip
        cd v
        sudo ./v symlink
    - name: Run tests
      run: |
        cd ..
        cd VlangBenchmarksVisualization
        v test .
