name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1.2.0
      with:
        v-version: latest
      id: v
    - name: Build repository app
      run: v .
    - name: Run V tests
      run: v test .
