name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y sudo build-essential libssl-dev libgc-dev unzip
    - name: Download V
      run: |
        wget https://github.com/vlang/v/releases/latest/download/v_linux.zip
        unzip v_linux.zip
        cd v
        sudo ./v symlink
    - name: Run tests
      run: |
        echo 'start ls'
        ls
        echo 'stop ls'
        v test tests/
