name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup V environment
      # You may pin to the exact commit or the version.
      # uses: nocturlab/setup-vlang-action@5cb58a1a4ae31497272bea0547d2df257e208641
      uses: nocturlab/setup-vlang-action@v1.2.0
    - name: Run tests
      run: |
        v test .
